/*
  filename: integralui.slide.js
  version : 22.1.0
  Copyright © 2016-2022 Lidor Systems. All rights reserved.

  This file is part of the "IntegralUI Web" Library. 
                                                                   
  The contents of this file are subject to the IntegralUI Web License, and may not be used except in compliance with the License.
  A copy of the License should have been installed in the product's root installation directory or it can be found at
  http://www.lidorsystems.com/products/web/studio/license-agreement.aspx.
                                                            
  This SOFTWARE is provided "AS IS", WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License for the specific language 
  governing rights and limitations under the License. Any infringement will be prosecuted under applicable laws.                           
*/
import{c as css,h as html}from"../external/lit-element.js";import{s as styleMap}from"../external/style-map.js";import IntegralUIBase from"./integralui.base.js";import{IntegralUIColorScheme,IntegralUITheme}from"./integralui.enums.js";import{iuiSlideDefaultStyle}from"../styles/default/integralui.slide.style.js";import{iuiSlideBarOfficeStyle}from"../styles/themes/office/integralui.slidebar.office.js";import{iuiSlideBarDarkStyle}from"../styles/color-schemes/dark/integralui.slidebar.dark.js";import{iuiSlideBarLightStyle}from"../styles/color-schemes/light/integralui.slidebar.light.js";class IntegralUISlide extends IntegralUIBase{_init(){super._init();this._currentControlStyleSettings=iuiSlideDefaultStyle;this._initStyle()}connectedCallback(){}disconnectedCallback(){}attributeChangedCallback(e,t,i){super.attributeChangedCallback(e,t,i)}static get properties(){return{}}get size(){return this._ctrlSize}set size(e){if(e){let t=!1;const i=this._ctrlSize;if(void 0!==e.width&&this._ctrlSize.width!==e.width){this._ctrlSize.width=e.width;t=!0}if(void 0!==e.height&&this._ctrlSize.height!==e.height){this._ctrlSize.height=e.height;t=!0}if(t){this._invokeEvent("sizeChanged",{size:this._ctrlSize});this.requestUpdate("size",i);this.updateLayout()}}}getSize(){return{width:this._elemRef?Math.floor(this._elemRef.offsetWidth):0,height:this._elemRef?Math.floor(this._elemRef.offsetHeight):0}}_updateColorSchemeSettings(e){this._currentColorSchemeSettings=css``;switch(e){case IntegralUIColorScheme.Dark:this._currentColorSchemeSettings.cssText=this._commonService.replaceAll(iuiSlideBarDarkStyle.cssText,"../../../icons",this._currentResourcePath);break;case IntegralUIColorScheme.Light:this._currentColorSchemeSettings.cssText=this._commonService.replaceAll(iuiSlideBarLightStyle.cssText,"../../../icons",this._currentResourcePath);break;default:this._currentColorSchemeSettings.cssText=""}}_updateThemeSettings(e){this._currentThemeSettings=css``;switch(e){case IntegralUITheme.Office:this._currentThemeSettings.cssText=this._commonService.replaceAll(iuiSlideBarOfficeStyle.cssText,"../../../icons",this._currentResourcePath);break;default:this._currentThemeSettings.cssText=""}}firstUpdated(e){this._updateReferences();this.updateLayout()}render(){return html`             <style>                 ${this._currentControlStyleSettings}                 ${this._currentThemeSettings}                 ${this._currentColorSchemeSettings}                 ${this._currentCustomStyle}             </style>             <div data-ctrl="slide" class="iui-slide" style=${styleMap(this._getControlStyle())}>                 <slot></slot>             </div>         `}_updateReferences(){this._elemRef=this.shadowRoot.querySelector("div[data-ctrl=slide]")}}window.customElements.define("iui-slide",IntegralUISlide);export default IntegralUISlide;